# Generated by Django 6.0.6 on 2026-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_genre', models.CharField(max_length=100)),
                ('game_platform', models.CharField(max_length=100)),
                ('game_developer', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('hours_played', models.IntegerField()),
                ('game_description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
